"""create countries table and fk restrictions

Revision ID: 95446ad1dcc7
Revises: b6791f4c77fb
Create Date: 2026-02-01 22:09:32.476134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95446ad1dcc7'
down_revision: Union[str, Sequence[str], None] = 'b6791f4c77fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'countries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('country_name', sa.String(length=255), nullable=True),
        sa.Column('code', sa.String(length=5), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(
        op.f('ix_countries_country_name'),
        'countries',
        ['country_name'], unique=False
    )
    op.create_index(
        op.f('ix_countries_id'),
        'countries',
        ['id'],
        unique=False
    )
    # ====
    op.execute("""
        ALTER TABLE parlons ADD COLUMN country_id INT NOT NULL AFTER id
    """)
    op.create_foreign_key(
        "fk_parlons_country",
        'parlons',
        'countries',
        ['country_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_parlons_country", "parlons", type_="foreignkey")
    op.drop_column("parlons", "country_id")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.drop_index(op.f("ix_countries_country_name"), table_name="countries")
    op.drop_table("countries")

    # ### end Alembic commands ###
